### ISSUE TITLE
Wrong detection

### ISSUE THREAD

**Issue by Halteproblem** [LokiResearch/fast-triangle-triangle-intersection#2]
The algorithm detects a non existing intersection of neighboring faces.

![image](https://user-images.githubusercontent.com/40931345/179221125-2de1a147-6d7b-4e13-ab1d-dc1c6639da13.png)
![image](https://user-images.githubusercontent.com/40931345/179221150-c11dc4d5-a72c-41c1-b719-37e1228e7e83.png)

**Comment by minitoine** [comment]
Hello. 

Thank you for your feedback, but I must admit I don't understand the problem. T1 and T2 have (0,0,0) and (0.5,-1,-1) in common, that's why there is a line intersection, the library is working as expected.

**Comment by minitoine** [comment]
If you are testing mesh triangles against each others, I suggest you to discard neighbors triangles.
You can have that information by building a HalfEdge Structure for example (see my other repos), or, by checking if the intersection points match one or two triangle vertices.

**Comment by Halteproblem** [comment]
Yes you are right that is expected behavior.

Thank you I will take a look at the half edge structure.
